### ISSUE TITLE
Paths with hyphens (-) no longer show up in tree

### ISSUE THREAD

**Issue by chucker** [trenz-gmbh/trenz-docs-api#29]

**Comment by ricardoboss** [comment]
Maybe a regression from this code https://github.com/trenz-gmbh/trenz-docs-api/commit/bb64935ea86031891f2e2a537d940bb936fc9b58#diff-e1b41639cc49ce2e4d9191c0342212365fa94cc816e20cae913ea1d8ca1615d1R17

Although this wouldn't explain why the node is hidden because it is hidden even if it has children (i.e. not only depends on the `HasContent` flag).

**Comment by ricardoboss** [comment]
The issue actually was that the `NavNodeOrderingService` checked the wrong filename and wasn't able to find it in the `.order` file, so they were implicitly hidden.

This was an unintended side-effect of rewriting the tree builder from using the index files to source files.
